<a href="https://colab.research.google.com/github/Sankalp-sa/Linear_Algebra_Assignment/blob/main/ALA_Ques_a_Vishal_Sharma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sympy as sym
import numpy as np

In [2]:
sym.init_printing(use_latex="mathjax")

In [3]:

def print_matrix(Title, M):
    print(Title)
    for row in M:
        print([round(x,3)+0 for x in row])

def Inverse(A,I):

    n=len(A)
    indices = list(range(n))
    
    for p in range(n): 
        divider = 1.0 / A[p][p]
      
        for j in range(n): 
          A[p][j] *= divider
          I[p][j] *= divider
      
        for i in range(n):
            Subtracter = A[i][p] 
            if(i == p):
                continue
            
            for j in range(n):
                A[i][j] = A[i][j] - Subtracter * A[p][j]
                I[i][j] = I[i][j] - Subtracter * I[p][j]
            
    print_matrix("inverse is",I) 

        

A1 = [[5,4,3,2,1],[4,3,2,1,5],[3,2,9,5,4],[2,1,5,4,3],[1,2,3,4,5]]
I1 = [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]
A2 = [[1,1,1,1,1],[1,2,3,1,2],[1,3,6,1,3],[0,0,0,1,1],[0,0,0,1,2]]
I2 = [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]
A3 = [[1,0,4,-6],[2,5,0,3],[-1,2,3,5],[2,1,-2,3]]
I3 = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
A4 = [[1,2,3,4],[-1,2,0,5],[0,4,-2,6],[2,4,0,6]]
I4 = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
A1test = np.array(A1)
I1test = np.array(I1)
A2test = np.array(A2)
I2test = np.array(I2)
A3test = np.array(A3)
I3test = np.array(I3)
A4test = np.array(A4)
I4test = np.array(I4)
Inverse(A1,I1)  
print()
print("Output by numpy")
print(np.linalg.inv(A1test))
print()
Inverse(A2,I2)
print()
print("Output by numpy")
print(np.linalg.inv(A2test))
print()
Inverse(A3,I3)
print()
print("Output by numpy")
print(np.linalg.inv(A3test))
print()
Inverse(A4,I4)
print()
print("Output by numpy")
print(np.linalg.inv(A4test))


inverse is
[0.022, 0.2, -0.333, 0.733, -0.378]
[0.244, -0.2, 0.333, -0.933, 0.444]
[-0.056, 0.0, 0.333, -0.333, -0.056]
[0.122, -0.2, -0.333, 0.533, 0.122]
[-0.167, 0.2, 0.0, 0.0, 0.033]

Output by numpy
[[ 2.22222222e-02  2.00000000e-01 -3.33333333e-01  7.33333333e-01
  -3.77777778e-01]
 [ 2.44444444e-01 -2.00000000e-01  3.33333333e-01 -9.33333333e-01
   4.44444444e-01]
 [-5.55555556e-02 -5.55111512e-17  3.33333333e-01 -3.33333333e-01
  -5.55555556e-02]
 [ 1.22222222e-01 -2.00000000e-01 -3.33333333e-01  5.33333333e-01
   1.22222222e-01]
 [-1.66666667e-01  2.00000000e-01  2.96059473e-17 -4.73695157e-17
   3.33333333e-02]]

inverse is
[3.0, -3.0, 1.0, -2.0, 1.0]
[-3.0, 5.0, -2.0, 1.0, -1.0]
[1.0, -2.0, 1.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 2.0, -1.0]
[0.0, 0.0, 0.0, -1.0, 1.0]

Output by numpy
[[ 3. -3.  1. -2.  1.]
 [-3.  5. -2.  1. -1.]
 [ 1. -2.  1. -0. -0.]
 [ 0.  0.  0.  2. -1.]
 [ 0.  0.  0. -1.  1.]]

inverse is
[0.233, -0.119, 0.038, 0.522]
[-0.082, 0.299, -0.094, -0.305]
[0.164, -0.09